export const dashboard1 = {
  "content_metadata_id": 29,
  "description": null,
  "hidden": false,
  "id": 22,
  "query_timezone": null,
  "readonly": false,
  "refresh_interval": null,
  "refresh_interval_to_i": null,
  "title": "CrossFilter",
  "user_id": 1,
  "space": {
    "name": "Shared",
    "parent_id": null,
    "id": 1,
    "content_metadata_id": 1,
    "creator_id": null,
    "external_id": null,
    "is_embed": false,
    "is_embed_shared_root": false,
    "is_embed_users_root": false,
    "is_personal": false,
    "is_personal_descendant": false,
    "is_shared_root": true,
    "is_users_root": false,
    "can": {
      "index": true,
      "show": true,
      "create": true,
      "see_admin_spaces": true,
      "update": false,
      "destroy": false,
      "move_content": true,
      "edit_content": true
    }
  },
  "background_color": null,
  "created_at": "2020-05-19T22:20:19.065-07:00",
  "crossfilter_enabled": true,
  "dashboard_elements": [
    {
      "body_text": null,
      "body_text_as_html": null,
      "dashboard_id": 22,
      "edit_uri": null,
      "id": 69,
      "look": null,
      "look_id": null,
      "lookml_link_id": null,
      "merge_result_id": null,
      "note_display": null,
      "note_state": null,
      "note_text": null,
      "note_text_as_html": null,
      "query": {
        "id": 247,
        "view": "users",
        "fields": [
          "users.gender",
          "users.count"
        ],
        "pivots": null,
        "fill_fields": null,
        "filters": null,
        "filter_expression": null,
        "sorts": [
          "users.count desc"
        ],
        "limit": "500",
        "column_limit": null,
        "total": null,
        "row_total": null,
        "vis_config": {
          "value_labels": "legend",
          "label_type": "labPer",
          "series_types": {},
          "type": "looker_pie",
          "defaults_version": 1
        },
        "filter_config": {},
        "visible_ui_sections": null,
        "slug": "GYXcN6R",
        "dynamic_fields": null,
        "client_id": "XkOpEANf6UxNV8O1sfzEmq",
        "share_url": "https://self-signed.looker.com:9999/x/XkOpEANf6UxNV8O1sfzEmq",
        "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/users?fields=users.gender,users.count&sorts=users.count+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22value_labels%22%3A%22legend%22%2C%22label_type%22%3A%22labPer%22%2C%22series_types%22%3A%7B%7D%2C%22type%22%3A%22looker_pie%22%2C%22defaults_version%22%3A1%7D&filter_config=%7B%7D&origin=share-expanded",
        "query_timezone": "America/Los_Angeles",
        "runtime": null,
        "model": "thelook"
      },
      "query_id": 247,
      "refresh_interval": null,
      "refresh_interval_to_i": null,
      "result_maker_id": 54,
      "subtitle_text": null,
      "title": "gender pie",
      "title_hidden": false,
      "title_text": null,
      "type": "vis",
      "alert_count": 0,
      "title_text_as_html": null,
      "subtitle_text_as_html": null,
      "result_maker": {
        "id": 54,
        "dynamic_fields": null,
        "filterables": [
          {
            "model": "thelook",
            "view": "users",
            "name": null,
            "listen": []
          }
        ],
        "sorts": [
          "users.count desc"
        ],
        "merge_result_id": null,
        "total": null,
        "query_id": 247,
        "sql_query_id": null,
        "query": {
          "id": 247,
          "view": "users",
          "fields": [
            "users.gender",
            "users.count"
          ],
          "pivots": null,
          "fill_fields": null,
          "filters": null,
          "filter_expression": null,
          "sorts": [
            "users.count desc"
          ],
          "limit": "500",
          "column_limit": null,
          "total": null,
          "row_total": null,
          "subtotals": null,
          "vis_config": {
            "value_labels": "legend",
            "label_type": "labPer",
            "series_types": {},
            "type": "looker_pie",
            "defaults_version": 1
          },
          "filter_config": {},
          "visible_ui_sections": null,
          "slug": "GYXcN6R",
          "dynamic_fields": null,
          "client_id": "XkOpEANf6UxNV8O1sfzEmq",
          "share_url": "https://self-signed.looker.com:9999/x/XkOpEANf6UxNV8O1sfzEmq",
          "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/users?fields=users.gender,users.count&sorts=users.count+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22value_labels%22%3A%22legend%22%2C%22label_type%22%3A%22labPer%22%2C%22series_types%22%3A%7B%7D%2C%22type%22%3A%22looker_pie%22%2C%22defaults_version%22%3A1%7D&filter_config=%7B%7D&origin=share-expanded",
          "url": "/explore/thelook/users?fields=users.gender,users.count&sorts=users.count+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22value_labels%22%3A%22legend%22%2C%22label_type%22%3A%22labPer%22%2C%22series_types%22%3A%7B%7D%2C%22type%22%3A%22looker_pie%22%2C%22defaults_version%22%3A1%7D&filter_config=%7B%7D",
          "query_timezone": "America/Los_Angeles",
          "runtime": null,
          "has_table_calculations": false,
          "model": "thelook",
          "can": {
            "run": true,
            "see_results": true,
            "explore": true,
            "create": true,
            "show": true,
            "cost_estimate": true,
            "index": true,
            "see_lookml": true,
            "see_aggregate_table_lookml": true,
            "see_derived_table_lookml": true,
            "see_sql": true,
            "generate_drill_links": true,
            "download": true,
            "download_unlimited": true,
            "schedule": true,
            "render": true
          }
        },
        "vis_config": {
          "value_labels": "legend",
          "label_type": "labPer",
          "series_types": {},
          "type": "looker_pie",
          "defaults_version": 1
        }
      },
      "can": {
        "create": true,
        "update": true,
        "destroy": true,
        "see_aggregate_table_lookml": true,
        "index": true,
        "show": true,
        "explore": true,
        "run": false,
        "show_errors": true,
        "find_and_replace": true
      }
    },
    {
      "body_text": null,
      "body_text_as_html": null,
      "dashboard_id": 22,
      "edit_uri": null,
      "id": 70,
      "look": null,
      "look_id": null,
      "lookml_link_id": null,
      "merge_result_id": null,
      "note_display": null,
      "note_state": null,
      "note_text": null,
      "note_text_as_html": null,
      "query": {
        "id": 252,
        "view": "users",
        "fields": [
          "users.count",
          "users.age",
          "users.age_tier"
        ],
        "pivots": null,
        "fill_fields": null,
        "filters": null,
        "filter_expression": null,
        "sorts": [
          "users.count desc"
        ],
        "limit": "500",
        "column_limit": null,
        "total": null,
        "row_total": null,
        "vis_config": {
          "x_axis_gridlines": false,
          "y_axis_gridlines": true,
          "show_view_names": false,
          "show_y_axis_labels": true,
          "show_y_axis_ticks": true,
          "y_axis_tick_density": "default",
          "y_axis_tick_density_custom": 5,
          "show_x_axis_label": true,
          "show_x_axis_ticks": true,
          "y_axis_scale_mode": "linear",
          "x_axis_reversed": false,
          "y_axis_reversed": false,
          "plot_size_by_field": false,
          "trellis": "",
          "stacking": "",
          "limit_displayed_rows": false,
          "legend_position": "center",
          "point_style": "none",
          "show_value_labels": false,
          "label_density": 25,
          "x_axis_scale": "auto",
          "y_axis_combined": true,
          "ordering": "none",
          "show_null_labels": false,
          "show_totals_labels": false,
          "show_silhouette": false,
          "totals_color": "#808080",
          "series_types": {},
          "type": "looker_column",
          "value_labels": "legend",
          "label_type": "labPer",
          "defaults_version": 1,
          "show_row_numbers": true,
          "transpose": false,
          "truncate_text": true,
          "hide_totals": false,
          "hide_row_totals": false,
          "size_to_fit": true,
          "table_theme": "white",
          "enable_conditional_formatting": false,
          "header_text_alignment": "left",
          "header_font_size": 12,
          "rows_font_size": 12,
          "conditional_formatting_include_totals": false,
          "conditional_formatting_include_nulls": false
        },
        "filter_config": {},
        "visible_ui_sections": null,
        "slug": "BJy6Ftx",
        "dynamic_fields": null,
        "client_id": "SEfHlYnMsOmewHE50llNB0",
        "share_url": "https://self-signed.looker.com:9999/x/SEfHlYnMsOmewHE50llNB0",
        "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/users?fields=users.count,users.age,users.age_tier&sorts=users.count+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%2C%22series_types%22%3A%7B%7D%2C%22type%22%3A%22looker_column%22%2C%22value_labels%22%3A%22legend%22%2C%22label_type%22%3A%22labPer%22%2C%22defaults_version%22%3A1%2C%22show_row_numbers%22%3Atrue%2C%22transpose%22%3Afalse%2C%22truncate_text%22%3Atrue%2C%22hide_totals%22%3Afalse%2C%22hide_row_totals%22%3Afalse%2C%22size_to_fit%22%3Atrue%2C%22table_theme%22%3A%22white%22%2C%22enable_conditional_formatting%22%3Afalse%2C%22header_text_alignment%22%3A%22left%22%2C%22header_font_size%22%3A12%2C%22rows_font_size%22%3A12%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%7D&filter_config=%7B%7D&origin=share-expanded",
        "query_timezone": "America/Los_Angeles",
        "runtime": null,
        "model": "thelook"
      },
      "query_id": 252,
      "refresh_interval": null,
      "refresh_interval_to_i": null,
      "result_maker_id": 55,
      "subtitle_text": null,
      "title": "age ageteir",
      "title_hidden": false,
      "title_text": null,
      "type": "vis",
      "alert_count": 0,
      "title_text_as_html": null,
      "subtitle_text_as_html": null,
      "result_maker": {
        "id": 55,
        "dynamic_fields": null,
        "filterables": [
          {
            "model": "thelook",
            "view": "users",
            "name": null,
            "listen": []
          }
        ],
        "sorts": [
          "users.count desc"
        ],
        "merge_result_id": null,
        "total": null,
        "query_id": 252,
        "sql_query_id": null,
        "query": {
          "id": 252,
          "view": "users",
          "fields": [
            "users.count",
            "users.age",
            "users.age_tier"
          ],
          "pivots": null,
          "fill_fields": null,
          "filters": null,
          "filter_expression": null,
          "sorts": [
            "users.count desc"
          ],
          "limit": "500",
          "column_limit": null,
          "total": null,
          "row_total": null,
          "subtotals": null,
          "vis_config": {
            "x_axis_gridlines": false,
            "y_axis_gridlines": true,
            "show_view_names": false,
            "show_y_axis_labels": true,
            "show_y_axis_ticks": true,
            "y_axis_tick_density": "default",
            "y_axis_tick_density_custom": 5,
            "show_x_axis_label": true,
            "show_x_axis_ticks": true,
            "y_axis_scale_mode": "linear",
            "x_axis_reversed": false,
            "y_axis_reversed": false,
            "plot_size_by_field": false,
            "trellis": "",
            "stacking": "",
            "limit_displayed_rows": false,
            "legend_position": "center",
            "point_style": "none",
            "show_value_labels": false,
            "label_density": 25,
            "x_axis_scale": "auto",
            "y_axis_combined": true,
            "ordering": "none",
            "show_null_labels": false,
            "show_totals_labels": false,
            "show_silhouette": false,
            "totals_color": "#808080",
            "series_types": {},
            "type": "looker_column",
            "value_labels": "legend",
            "label_type": "labPer",
            "defaults_version": 1,
            "show_row_numbers": true,
            "transpose": false,
            "truncate_text": true,
            "hide_totals": false,
            "hide_row_totals": false,
            "size_to_fit": true,
            "table_theme": "white",
            "enable_conditional_formatting": false,
            "header_text_alignment": "left",
            "header_font_size": 12,
            "rows_font_size": 12,
            "conditional_formatting_include_totals": false,
            "conditional_formatting_include_nulls": false
          },
          "filter_config": {},
          "visible_ui_sections": null,
          "slug": "BJy6Ftx",
          "dynamic_fields": null,
          "client_id": "SEfHlYnMsOmewHE50llNB0",
          "share_url": "https://self-signed.looker.com:9999/x/SEfHlYnMsOmewHE50llNB0",
          "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/users?fields=users.count,users.age,users.age_tier&sorts=users.count+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%2C%22series_types%22%3A%7B%7D%2C%22type%22%3A%22looker_column%22%2C%22value_labels%22%3A%22legend%22%2C%22label_type%22%3A%22labPer%22%2C%22defaults_version%22%3A1%2C%22show_row_numbers%22%3Atrue%2C%22transpose%22%3Afalse%2C%22truncate_text%22%3Atrue%2C%22hide_totals%22%3Afalse%2C%22hide_row_totals%22%3Afalse%2C%22size_to_fit%22%3Atrue%2C%22table_theme%22%3A%22white%22%2C%22enable_conditional_formatting%22%3Afalse%2C%22header_text_alignment%22%3A%22left%22%2C%22header_font_size%22%3A12%2C%22rows_font_size%22%3A12%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%7D&filter_config=%7B%7D&origin=share-expanded",
          "url": "/explore/thelook/users?fields=users.count,users.age,users.age_tier&sorts=users.count+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%2C%22series_types%22%3A%7B%7D%2C%22type%22%3A%22looker_column%22%2C%22value_labels%22%3A%22legend%22%2C%22label_type%22%3A%22labPer%22%2C%22defaults_version%22%3A1%2C%22show_row_numbers%22%3Atrue%2C%22transpose%22%3Afalse%2C%22truncate_text%22%3Atrue%2C%22hide_totals%22%3Afalse%2C%22hide_row_totals%22%3Afalse%2C%22size_to_fit%22%3Atrue%2C%22table_theme%22%3A%22white%22%2C%22enable_conditional_formatting%22%3Afalse%2C%22header_text_alignment%22%3A%22left%22%2C%22header_font_size%22%3A12%2C%22rows_font_size%22%3A12%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%7D&filter_config=%7B%7D",
          "query_timezone": "America/Los_Angeles",
          "runtime": null,
          "has_table_calculations": false,
          "model": "thelook",
          "can": {
            "run": true,
            "see_results": true,
            "explore": true,
            "create": true,
            "show": true,
            "cost_estimate": true,
            "index": true,
            "see_lookml": true,
            "see_aggregate_table_lookml": true,
            "see_derived_table_lookml": true,
            "see_sql": true,
            "generate_drill_links": true,
            "download": true,
            "download_unlimited": true,
            "schedule": true,
            "render": true
          }
        },
        "vis_config": {
          "x_axis_gridlines": false,
          "y_axis_gridlines": true,
          "show_view_names": false,
          "show_y_axis_labels": true,
          "show_y_axis_ticks": true,
          "y_axis_tick_density": "default",
          "y_axis_tick_density_custom": 5,
          "show_x_axis_label": true,
          "show_x_axis_ticks": true,
          "y_axis_scale_mode": "linear",
          "x_axis_reversed": false,
          "y_axis_reversed": false,
          "plot_size_by_field": false,
          "trellis": "",
          "stacking": "",
          "limit_displayed_rows": false,
          "legend_position": "center",
          "point_style": "none",
          "show_value_labels": false,
          "label_density": 25,
          "x_axis_scale": "auto",
          "y_axis_combined": true,
          "ordering": "none",
          "show_null_labels": false,
          "show_totals_labels": false,
          "show_silhouette": false,
          "totals_color": "#808080",
          "series_types": {},
          "type": "looker_column",
          "value_labels": "legend",
          "label_type": "labPer",
          "defaults_version": 1,
          "show_row_numbers": true,
          "transpose": false,
          "truncate_text": true,
          "hide_totals": false,
          "hide_row_totals": false,
          "size_to_fit": true,
          "table_theme": "white",
          "enable_conditional_formatting": false,
          "header_text_alignment": "left",
          "header_font_size": 12,
          "rows_font_size": 12,
          "conditional_formatting_include_totals": false,
          "conditional_formatting_include_nulls": false
        }
      },
      "can": {
        "create": true,
        "update": true,
        "destroy": true,
        "see_aggregate_table_lookml": true,
        "index": true,
        "show": true,
        "explore": true,
        "run": false,
        "show_errors": true,
        "find_and_replace": true
      }
    }
  ],
  "dashboard_filters": [],
  "dashboard_layouts": [
    {
      "id": 22,
      "dashboard_id": 22,
      "type": "newspaper",
      "active": true,
      "column_width": null,
      "width": null,
      "deleted": false,
      "dashboard_layout_components": [
        {
          "id": 69,
          "dashboard_layout_id": 22,
          "dashboard_element_id": 69,
          "row": 0,
          "column": 0,
          "width": 15,
          "height": 7,
          "deleted": false
        },
        {
          "id": 70,
          "dashboard_layout_id": 22,
          "dashboard_element_id": 70,
          "row": 0,
          "column": 15,
          "width": 9,
          "height": 7,
          "deleted": false
        }
      ]
    }
  ],
  "deleted_at": null,
  "deleter_id": null,
  "edit_uri": null,
  "favorite_count": 0,
  "last_accessed_at": "2020-05-20T22:41:13.657-07:00",
  "load_configuration": "cache_run",
  "show_filters_bar": null,
  "show_title": null,
  "slug": "GoavXlnZAhbOIjwvcKowbo",
  "space_id": 1,
  "text_tile_text_color": null,
  "tile_background_color": null,
  "tile_text_color": null,
  "title_color": null,
  "view_count": 2,
  "preferred_viewer": "dashboards-next",
  "content_favorite_id": null,
  "model": null,
  "deleted": false,
  "last_viewed_at": "2020-06-17T12:52:41.768-07:00",
  "can": {
    "download": true,
    "see_aggregate_table_lookml": true,
    "index": true,
    "show": true,
    "copy": true,
    "run": true,
    "create": true,
    "move": true,
    "update": true,
    "destroy": true,
    "recover": true,
    "see_lookml": true,
    "schedule": true,
    "render": true
  }
}
