export const dashboard2 = {
  "content_metadata_id": 70,
  "description": null,
  "hidden": false,
  "id": 59,
  "query_timezone": null,
  "readonly": false,
  "refresh_interval": null,
  "refresh_interval_to_i": null,
  "title": "June 2020 Hackathon",
  "user_id": 1,
  "space": {
    "name": "Shared",
    "parent_id": null,
    "id": 1,
    "content_metadata_id": 1,
    "creator_id": null,
    "external_id": null,
    "is_embed": false,
    "is_embed_shared_root": false,
    "is_embed_users_root": false,
    "is_personal": false,
    "is_personal_descendant": false,
    "is_shared_root": true,
    "is_users_root": false,
    "can": {
      "index": true,
      "show": true,
      "create": true,
      "see_admin_spaces": true,
      "update": false,
      "destroy": false,
      "move_content": true,
      "edit_content": true
    }
  },
  "background_color": null,
  "created_at": "2020-06-17T12:14:37.124-07:00",
  "crossfilter_enabled": false,
  "dashboard_elements": [
    {
      "body_text": "",
      "body_text_as_html": null,
      "dashboard_id": 59,
      "edit_uri": null,
      "id": 110,
      "look": null,
      "look_id": null,
      "lookml_link_id": null,
      "merge_result_id": null,
      "note_display": null,
      "note_state": null,
      "note_text": null,
      "note_text_as_html": null,
      "query": null,
      "query_id": null,
      "refresh_interval": null,
      "refresh_interval_to_i": null,
      "result_maker_id": null,
      "subtitle_text": "Keep up to date with current orders  and historical values",
      "title": null,
      "title_hidden": false,
      "title_text": "Orders dashboard",
      "type": "text",
      "alert_count": 0,
      "title_text_as_html": "Orders dashboard",
      "subtitle_text_as_html": "Keep up to date with current orders  and historical values",
      "result_maker": null,
      "can": {
        "create": true,
        "update": true,
        "destroy": true,
        "see_aggregate_table_lookml": false,
        "index": true,
        "show": true,
        "explore": false,
        "run": false,
        "show_errors": true,
        "find_and_replace": true
      }
    },
    {
      "body_text": null,
      "body_text_as_html": null,
      "dashboard_id": 59,
      "edit_uri": null,
      "id": 106,
      "look": null,
      "look_id": null,
      "lookml_link_id": null,
      "merge_result_id": null,
      "note_display": null,
      "note_state": null,
      "note_text": null,
      "note_text_as_html": null,
      "query": {
        "id": 382,
        "view": "orders",
        "fields": [
          "orders.created_date",
          "orders.profit_per_user"
        ],
        "pivots": null,
        "fill_fields": [
          "orders.created_date"
        ],
        "filters": null,
        "filter_expression": null,
        "sorts": [
          "orders.created_date desc"
        ],
        "limit": "500",
        "column_limit": null,
        "total": null,
        "row_total": null,
        "vis_config": {
          "x_axis_gridlines": false,
          "y_axis_gridlines": true,
          "show_view_names": false,
          "show_y_axis_labels": true,
          "show_y_axis_ticks": true,
          "y_axis_tick_density": "default",
          "y_axis_tick_density_custom": 5,
          "show_x_axis_label": true,
          "show_x_axis_ticks": true,
          "y_axis_scale_mode": "linear",
          "x_axis_reversed": false,
          "y_axis_reversed": false,
          "plot_size_by_field": false,
          "trellis": "",
          "stacking": "",
          "limit_displayed_rows": false,
          "legend_position": "center",
          "point_style": "none",
          "show_value_labels": false,
          "label_density": 25,
          "x_axis_scale": "auto",
          "y_axis_combined": true,
          "show_null_points": true,
          "interpolation": "linear",
          "type": "looker_line",
          "defaults_version": 1,
          "series_types": {},
          "ordering": "none",
          "show_null_labels": false,
          "show_totals_labels": false,
          "show_silhouette": false,
          "totals_color": "#808080"
        },
        "filter_config": {},
        "visible_ui_sections": null,
        "slug": "McpCcYm",
        "dynamic_fields": null,
        "client_id": "jSdeDKGK4TOWwm3MqHPfwo",
        "share_url": "https://self-signed.looker.com:9999/x/jSdeDKGK4TOWwm3MqHPfwo",
        "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/orders?fields=orders.created_date,orders.profit_per_user&fill_fields=orders.created_date&sorts=orders.created_date+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22type%22%3A%22looker_line%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D&origin=share-expanded",
        "query_timezone": "America/Los_Angeles",
        "runtime": null,
        "model": "thelook"
      },
      "query_id": 382,
      "refresh_interval": null,
      "refresh_interval_to_i": null,
      "result_maker_id": 81,
      "subtitle_text": null,
      "title": "title",
      "title_hidden": true,
      "title_text": null,
      "type": "vis",
      "alert_count": 0,
      "title_text_as_html": null,
      "subtitle_text_as_html": null,
      "result_maker": {
        "id": 81,
        "dynamic_fields": null,
        "filterables": [
          {
            "model": "thelook",
            "view": "orders",
            "name": null,
            "listen": [
              {
                "dashboard_filter_name": "Created Date",
                "field": "orders.created_date"
              }
            ]
          }
        ],
        "sorts": [
          "orders.created_date desc"
        ],
        "merge_result_id": null,
        "total": null,
        "query_id": 382,
        "sql_query_id": null,
        "query": {
          "id": 382,
          "view": "orders",
          "fields": [
            "orders.created_date",
            "orders.profit_per_user"
          ],
          "pivots": null,
          "fill_fields": [
            "orders.created_date"
          ],
          "filters": null,
          "filter_expression": null,
          "sorts": [
            "orders.created_date desc"
          ],
          "limit": "500",
          "column_limit": null,
          "total": null,
          "row_total": null,
          "subtotals": null,
          "vis_config": {
            "x_axis_gridlines": false,
            "y_axis_gridlines": true,
            "show_view_names": false,
            "show_y_axis_labels": true,
            "show_y_axis_ticks": true,
            "y_axis_tick_density": "default",
            "y_axis_tick_density_custom": 5,
            "show_x_axis_label": true,
            "show_x_axis_ticks": true,
            "y_axis_scale_mode": "linear",
            "x_axis_reversed": false,
            "y_axis_reversed": false,
            "plot_size_by_field": false,
            "trellis": "",
            "stacking": "",
            "limit_displayed_rows": false,
            "legend_position": "center",
            "point_style": "none",
            "show_value_labels": false,
            "label_density": 25,
            "x_axis_scale": "auto",
            "y_axis_combined": true,
            "show_null_points": true,
            "interpolation": "linear",
            "type": "looker_line",
            "defaults_version": 1,
            "series_types": {},
            "ordering": "none",
            "show_null_labels": false,
            "show_totals_labels": false,
            "show_silhouette": false,
            "totals_color": "#808080"
          },
          "filter_config": {},
          "visible_ui_sections": null,
          "slug": "McpCcYm",
          "dynamic_fields": null,
          "client_id": "jSdeDKGK4TOWwm3MqHPfwo",
          "share_url": "https://self-signed.looker.com:9999/x/jSdeDKGK4TOWwm3MqHPfwo",
          "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/orders?fields=orders.created_date,orders.profit_per_user&fill_fields=orders.created_date&sorts=orders.created_date+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22type%22%3A%22looker_line%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D&origin=share-expanded",
          "url": "/explore/thelook/orders?fields=orders.created_date,orders.profit_per_user&fill_fields=orders.created_date&sorts=orders.created_date+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22type%22%3A%22looker_line%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D",
          "query_timezone": "America/Los_Angeles",
          "runtime": null,
          "has_table_calculations": false,
          "model": "thelook",
          "can": {
            "run": true,
            "see_results": true,
            "explore": true,
            "create": true,
            "show": true,
            "cost_estimate": true,
            "index": true,
            "see_lookml": true,
            "see_aggregate_table_lookml": true,
            "see_derived_table_lookml": true,
            "see_sql": true,
            "generate_drill_links": true,
            "download": true,
            "download_unlimited": true,
            "schedule": true,
            "render": true
          }
        },
        "vis_config": {
          "x_axis_gridlines": false,
          "y_axis_gridlines": true,
          "show_view_names": false,
          "show_y_axis_labels": true,
          "show_y_axis_ticks": true,
          "y_axis_tick_density": "default",
          "y_axis_tick_density_custom": 5,
          "show_x_axis_label": true,
          "show_x_axis_ticks": true,
          "y_axis_scale_mode": "linear",
          "x_axis_reversed": false,
          "y_axis_reversed": false,
          "plot_size_by_field": false,
          "trellis": "",
          "stacking": "",
          "limit_displayed_rows": false,
          "legend_position": "center",
          "point_style": "none",
          "show_value_labels": false,
          "label_density": 25,
          "x_axis_scale": "auto",
          "y_axis_combined": true,
          "show_null_points": true,
          "interpolation": "linear",
          "type": "looker_line",
          "defaults_version": 1,
          "series_types": {},
          "ordering": "none",
          "show_null_labels": false,
          "show_totals_labels": false,
          "show_silhouette": false,
          "totals_color": "#808080"
        }
      },
      "can": {
        "create": true,
        "update": true,
        "destroy": true,
        "see_aggregate_table_lookml": true,
        "index": true,
        "show": true,
        "explore": true,
        "run": false,
        "show_errors": true,
        "find_and_replace": true
      }
    },
    {
      "body_text": null,
      "body_text_as_html": null,
      "dashboard_id": 59,
      "edit_uri": null,
      "id": 107,
      "look": null,
      "look_id": null,
      "lookml_link_id": null,
      "merge_result_id": null,
      "note_display": null,
      "note_state": null,
      "note_text": null,
      "note_text_as_html": null,
      "query": {
        "id": 384,
        "view": "orders",
        "fields": [
          "orders.created_date",
          "orders.profit_per_user",
          "users.gender"
        ],
        "pivots": [
          "users.gender"
        ],
        "fill_fields": [
          "orders.created_date"
        ],
        "filters": null,
        "filter_expression": null,
        "sorts": [
          "orders.created_date desc",
          "users.gender"
        ],
        "limit": "500",
        "column_limit": null,
        "total": null,
        "row_total": null,
        "vis_config": {
          "x_axis_gridlines": false,
          "y_axis_gridlines": true,
          "show_view_names": false,
          "show_y_axis_labels": true,
          "show_y_axis_ticks": true,
          "y_axis_tick_density": "default",
          "y_axis_tick_density_custom": 5,
          "show_x_axis_label": true,
          "show_x_axis_ticks": true,
          "y_axis_scale_mode": "linear",
          "x_axis_reversed": false,
          "y_axis_reversed": false,
          "plot_size_by_field": false,
          "trellis": "",
          "stacking": "",
          "limit_displayed_rows": false,
          "legend_position": "center",
          "point_style": "none",
          "show_value_labels": false,
          "label_density": 25,
          "x_axis_scale": "auto",
          "y_axis_combined": true,
          "show_null_points": true,
          "interpolation": "linear",
          "type": "looker_line",
          "defaults_version": 1,
          "series_types": {},
          "ordering": "none",
          "show_null_labels": false,
          "show_totals_labels": false,
          "show_silhouette": false,
          "totals_color": "#808080"
        },
        "filter_config": {},
        "visible_ui_sections": null,
        "slug": "MJjpTYF",
        "dynamic_fields": null,
        "client_id": "KRTtyper5QeEEYijFVgTDE",
        "share_url": "https://self-signed.looker.com:9999/x/KRTtyper5QeEEYijFVgTDE",
        "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/orders?fields=orders.created_date,orders.profit_per_user,users.gender&pivots=users.gender&fill_fields=orders.created_date&sorts=orders.created_date+desc,users.gender&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22type%22%3A%22looker_line%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D&origin=share-expanded",
        "query_timezone": "America/Los_Angeles",
        "runtime": null,
        "model": "thelook"
      },
      "query_id": 384,
      "refresh_interval": null,
      "refresh_interval_to_i": null,
      "result_maker_id": 82,
      "subtitle_text": null,
      "title": "by gender",
      "title_hidden": true,
      "title_text": null,
      "type": "vis",
      "alert_count": 0,
      "title_text_as_html": null,
      "subtitle_text_as_html": null,
      "result_maker": {
        "id": 82,
        "dynamic_fields": null,
        "filterables": [
          {
            "model": "thelook",
            "view": "orders",
            "name": null,
            "listen": [
              {
                "dashboard_filter_name": "Created Date",
                "field": "orders.created_date"
              }
            ]
          }
        ],
        "sorts": [
          "orders.created_date desc",
          "users.gender"
        ],
        "merge_result_id": null,
        "total": null,
        "query_id": 384,
        "sql_query_id": null,
        "query": {
          "id": 384,
          "view": "orders",
          "fields": [
            "orders.created_date",
            "orders.profit_per_user",
            "users.gender"
          ],
          "pivots": [
            "users.gender"
          ],
          "fill_fields": [
            "orders.created_date"
          ],
          "filters": null,
          "filter_expression": null,
          "sorts": [
            "orders.created_date desc",
            "users.gender"
          ],
          "limit": "500",
          "column_limit": null,
          "total": null,
          "row_total": null,
          "subtotals": null,
          "vis_config": {
            "x_axis_gridlines": false,
            "y_axis_gridlines": true,
            "show_view_names": false,
            "show_y_axis_labels": true,
            "show_y_axis_ticks": true,
            "y_axis_tick_density": "default",
            "y_axis_tick_density_custom": 5,
            "show_x_axis_label": true,
            "show_x_axis_ticks": true,
            "y_axis_scale_mode": "linear",
            "x_axis_reversed": false,
            "y_axis_reversed": false,
            "plot_size_by_field": false,
            "trellis": "",
            "stacking": "",
            "limit_displayed_rows": false,
            "legend_position": "center",
            "point_style": "none",
            "show_value_labels": false,
            "label_density": 25,
            "x_axis_scale": "auto",
            "y_axis_combined": true,
            "show_null_points": true,
            "interpolation": "linear",
            "type": "looker_line",
            "defaults_version": 1,
            "series_types": {},
            "ordering": "none",
            "show_null_labels": false,
            "show_totals_labels": false,
            "show_silhouette": false,
            "totals_color": "#808080"
          },
          "filter_config": {},
          "visible_ui_sections": null,
          "slug": "MJjpTYF",
          "dynamic_fields": null,
          "client_id": "KRTtyper5QeEEYijFVgTDE",
          "share_url": "https://self-signed.looker.com:9999/x/KRTtyper5QeEEYijFVgTDE",
          "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/orders?fields=orders.created_date,orders.profit_per_user,users.gender&pivots=users.gender&fill_fields=orders.created_date&sorts=orders.created_date+desc,users.gender&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22type%22%3A%22looker_line%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D&origin=share-expanded",
          "url": "/explore/thelook/orders?fields=orders.created_date,orders.profit_per_user,users.gender&pivots=users.gender&fill_fields=orders.created_date&sorts=orders.created_date+desc,users.gender&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22type%22%3A%22looker_line%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D",
          "query_timezone": "America/Los_Angeles",
          "runtime": null,
          "has_table_calculations": false,
          "model": "thelook",
          "can": {
            "run": true,
            "see_results": true,
            "explore": true,
            "create": true,
            "show": true,
            "cost_estimate": true,
            "index": true,
            "see_lookml": true,
            "see_aggregate_table_lookml": true,
            "see_derived_table_lookml": true,
            "see_sql": true,
            "generate_drill_links": true,
            "download": true,
            "download_unlimited": true,
            "schedule": true,
            "render": true
          }
        },
        "vis_config": {
          "x_axis_gridlines": false,
          "y_axis_gridlines": true,
          "show_view_names": false,
          "show_y_axis_labels": true,
          "show_y_axis_ticks": true,
          "y_axis_tick_density": "default",
          "y_axis_tick_density_custom": 5,
          "show_x_axis_label": true,
          "show_x_axis_ticks": true,
          "y_axis_scale_mode": "linear",
          "x_axis_reversed": false,
          "y_axis_reversed": false,
          "plot_size_by_field": false,
          "trellis": "",
          "stacking": "",
          "limit_displayed_rows": false,
          "legend_position": "center",
          "point_style": "none",
          "show_value_labels": false,
          "label_density": 25,
          "x_axis_scale": "auto",
          "y_axis_combined": true,
          "show_null_points": true,
          "interpolation": "linear",
          "type": "looker_line",
          "defaults_version": 1,
          "series_types": {},
          "ordering": "none",
          "show_null_labels": false,
          "show_totals_labels": false,
          "show_silhouette": false,
          "totals_color": "#808080"
        }
      },
      "can": {
        "create": true,
        "update": true,
        "destroy": true,
        "see_aggregate_table_lookml": true,
        "index": true,
        "show": true,
        "explore": true,
        "run": false,
        "show_errors": true,
        "find_and_replace": true
      }
    },
    {
      "body_text": null,
      "body_text_as_html": null,
      "dashboard_id": 59,
      "edit_uri": null,
      "id": 108,
      "look": null,
      "look_id": null,
      "lookml_link_id": null,
      "merge_result_id": null,
      "note_display": null,
      "note_state": null,
      "note_text": null,
      "note_text_as_html": null,
      "query": {
        "id": 391,
        "view": "orders",
        "fields": [
          "orders.created_date",
          "orders.count"
        ],
        "pivots": null,
        "fill_fields": [
          "orders.created_date"
        ],
        "filters": null,
        "filter_expression": null,
        "sorts": [
          "orders.created_date desc"
        ],
        "limit": "500",
        "column_limit": null,
        "total": null,
        "row_total": null,
        "vis_config": {
          "custom_color_enabled": true,
          "show_single_value_title": true,
          "show_comparison": false,
          "comparison_type": "value",
          "comparison_reverse_colors": false,
          "show_comparison_label": true,
          "enable_conditional_formatting": false,
          "conditional_formatting_include_totals": false,
          "conditional_formatting_include_nulls": false,
          "type": "single_value",
          "x_axis_gridlines": false,
          "y_axis_gridlines": true,
          "show_view_names": false,
          "show_y_axis_labels": true,
          "show_y_axis_ticks": true,
          "y_axis_tick_density": "default",
          "y_axis_tick_density_custom": 5,
          "show_x_axis_label": true,
          "show_x_axis_ticks": true,
          "y_axis_scale_mode": "linear",
          "x_axis_reversed": false,
          "y_axis_reversed": false,
          "plot_size_by_field": false,
          "trellis": "",
          "stacking": "",
          "limit_displayed_rows": false,
          "legend_position": "center",
          "point_style": "none",
          "show_value_labels": false,
          "label_density": 25,
          "x_axis_scale": "auto",
          "y_axis_combined": true,
          "show_null_points": true,
          "interpolation": "linear",
          "defaults_version": 1,
          "series_types": {},
          "ordering": "none",
          "show_null_labels": false,
          "show_totals_labels": false,
          "show_silhouette": false,
          "totals_color": "#808080"
        },
        "filter_config": {},
        "visible_ui_sections": null,
        "slug": "sZ74yB5",
        "dynamic_fields": null,
        "client_id": "vFVqf3NHo6n8YDIeWJP7mR",
        "share_url": "https://self-signed.looker.com:9999/x/vFVqf3NHo6n8YDIeWJP7mR",
        "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/orders?fields=orders.created_date,orders.count&fill_fields=orders.created_date&sorts=orders.created_date+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22custom_color_enabled%22%3Atrue%2C%22show_single_value_title%22%3Atrue%2C%22show_comparison%22%3Afalse%2C%22comparison_type%22%3A%22value%22%2C%22comparison_reverse_colors%22%3Afalse%2C%22show_comparison_label%22%3Atrue%2C%22enable_conditional_formatting%22%3Afalse%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%2C%22type%22%3A%22single_value%22%2C%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D&origin=share-expanded",
        "query_timezone": "America/Los_Angeles",
        "runtime": null,
        "model": "thelook"
      },
      "query_id": 391,
      "refresh_interval": null,
      "refresh_interval_to_i": null,
      "result_maker_id": 83,
      "subtitle_text": null,
      "title": "Orders today",
      "title_hidden": false,
      "title_text": null,
      "type": "vis",
      "alert_count": 0,
      "title_text_as_html": null,
      "subtitle_text_as_html": null,
      "result_maker": {
        "id": 83,
        "dynamic_fields": null,
        "filterables": [
          {
            "model": "thelook",
            "view": "orders",
            "name": null,
            "listen": [
              {
                "dashboard_filter_name": "Created Date",
                "field": "orders.created_date"
              }
            ]
          }
        ],
        "sorts": [
          "orders.created_date desc"
        ],
        "merge_result_id": null,
        "total": null,
        "query_id": 391,
        "sql_query_id": null,
        "query": {
          "id": 391,
          "view": "orders",
          "fields": [
            "orders.created_date",
            "orders.count"
          ],
          "pivots": null,
          "fill_fields": [
            "orders.created_date"
          ],
          "filters": null,
          "filter_expression": null,
          "sorts": [
            "orders.created_date desc"
          ],
          "limit": "500",
          "column_limit": null,
          "total": null,
          "row_total": null,
          "subtotals": null,
          "vis_config": {
            "custom_color_enabled": true,
            "show_single_value_title": true,
            "show_comparison": false,
            "comparison_type": "value",
            "comparison_reverse_colors": false,
            "show_comparison_label": true,
            "enable_conditional_formatting": false,
            "conditional_formatting_include_totals": false,
            "conditional_formatting_include_nulls": false,
            "type": "single_value",
            "x_axis_gridlines": false,
            "y_axis_gridlines": true,
            "show_view_names": false,
            "show_y_axis_labels": true,
            "show_y_axis_ticks": true,
            "y_axis_tick_density": "default",
            "y_axis_tick_density_custom": 5,
            "show_x_axis_label": true,
            "show_x_axis_ticks": true,
            "y_axis_scale_mode": "linear",
            "x_axis_reversed": false,
            "y_axis_reversed": false,
            "plot_size_by_field": false,
            "trellis": "",
            "stacking": "",
            "limit_displayed_rows": false,
            "legend_position": "center",
            "point_style": "none",
            "show_value_labels": false,
            "label_density": 25,
            "x_axis_scale": "auto",
            "y_axis_combined": true,
            "show_null_points": true,
            "interpolation": "linear",
            "defaults_version": 1,
            "series_types": {},
            "ordering": "none",
            "show_null_labels": false,
            "show_totals_labels": false,
            "show_silhouette": false,
            "totals_color": "#808080"
          },
          "filter_config": {},
          "visible_ui_sections": null,
          "slug": "sZ74yB5",
          "dynamic_fields": null,
          "client_id": "vFVqf3NHo6n8YDIeWJP7mR",
          "share_url": "https://self-signed.looker.com:9999/x/vFVqf3NHo6n8YDIeWJP7mR",
          "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/orders?fields=orders.created_date,orders.count&fill_fields=orders.created_date&sorts=orders.created_date+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22custom_color_enabled%22%3Atrue%2C%22show_single_value_title%22%3Atrue%2C%22show_comparison%22%3Afalse%2C%22comparison_type%22%3A%22value%22%2C%22comparison_reverse_colors%22%3Afalse%2C%22show_comparison_label%22%3Atrue%2C%22enable_conditional_formatting%22%3Afalse%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%2C%22type%22%3A%22single_value%22%2C%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D&origin=share-expanded",
          "url": "/explore/thelook/orders?fields=orders.created_date,orders.count&fill_fields=orders.created_date&sorts=orders.created_date+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22custom_color_enabled%22%3Atrue%2C%22show_single_value_title%22%3Atrue%2C%22show_comparison%22%3Afalse%2C%22comparison_type%22%3A%22value%22%2C%22comparison_reverse_colors%22%3Afalse%2C%22show_comparison_label%22%3Atrue%2C%22enable_conditional_formatting%22%3Afalse%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%2C%22type%22%3A%22single_value%22%2C%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D",
          "query_timezone": "America/Los_Angeles",
          "runtime": null,
          "has_table_calculations": false,
          "model": "thelook",
          "can": {
            "run": true,
            "see_results": true,
            "explore": true,
            "create": true,
            "show": true,
            "cost_estimate": true,
            "index": true,
            "see_lookml": true,
            "see_aggregate_table_lookml": true,
            "see_derived_table_lookml": true,
            "see_sql": true,
            "generate_drill_links": true,
            "download": true,
            "download_unlimited": true,
            "schedule": true,
            "render": true
          }
        },
        "vis_config": {
          "custom_color_enabled": true,
          "show_single_value_title": true,
          "show_comparison": false,
          "comparison_type": "value",
          "comparison_reverse_colors": false,
          "show_comparison_label": true,
          "enable_conditional_formatting": false,
          "conditional_formatting_include_totals": false,
          "conditional_formatting_include_nulls": false,
          "type": "single_value",
          "x_axis_gridlines": false,
          "y_axis_gridlines": true,
          "show_view_names": false,
          "show_y_axis_labels": true,
          "show_y_axis_ticks": true,
          "y_axis_tick_density": "default",
          "y_axis_tick_density_custom": 5,
          "show_x_axis_label": true,
          "show_x_axis_ticks": true,
          "y_axis_scale_mode": "linear",
          "x_axis_reversed": false,
          "y_axis_reversed": false,
          "plot_size_by_field": false,
          "trellis": "",
          "stacking": "",
          "limit_displayed_rows": false,
          "legend_position": "center",
          "point_style": "none",
          "show_value_labels": false,
          "label_density": 25,
          "x_axis_scale": "auto",
          "y_axis_combined": true,
          "show_null_points": true,
          "interpolation": "linear",
          "defaults_version": 1,
          "series_types": {},
          "ordering": "none",
          "show_null_labels": false,
          "show_totals_labels": false,
          "show_silhouette": false,
          "totals_color": "#808080"
        }
      },
      "can": {
        "create": true,
        "update": true,
        "destroy": true,
        "see_aggregate_table_lookml": true,
        "index": true,
        "show": true,
        "explore": true,
        "run": false,
        "show_errors": true,
        "find_and_replace": true
      }
    },
    {
      "body_text": null,
      "body_text_as_html": null,
      "dashboard_id": 59,
      "edit_uri": null,
      "id": 109,
      "look": null,
      "look_id": null,
      "lookml_link_id": null,
      "merge_result_id": null,
      "note_display": null,
      "note_state": null,
      "note_text": null,
      "note_text_as_html": null,
      "query": {
        "id": 395,
        "view": "orders",
        "fields": [
          "orders.created_date",
          "orders.average_total_amount_of_order_usd"
        ],
        "pivots": null,
        "fill_fields": [
          "orders.created_date"
        ],
        "filters": null,
        "filter_expression": null,
        "sorts": [
          "orders.created_date desc"
        ],
        "limit": "500",
        "column_limit": null,
        "total": null,
        "row_total": null,
        "vis_config": {
          "custom_color_enabled": true,
          "show_single_value_title": true,
          "show_comparison": false,
          "comparison_type": "value",
          "comparison_reverse_colors": false,
          "show_comparison_label": true,
          "enable_conditional_formatting": false,
          "conditional_formatting_include_totals": false,
          "conditional_formatting_include_nulls": false,
          "type": "single_value",
          "x_axis_gridlines": false,
          "y_axis_gridlines": true,
          "show_view_names": false,
          "show_y_axis_labels": true,
          "show_y_axis_ticks": true,
          "y_axis_tick_density": "default",
          "y_axis_tick_density_custom": 5,
          "show_x_axis_label": true,
          "show_x_axis_ticks": true,
          "y_axis_scale_mode": "linear",
          "x_axis_reversed": false,
          "y_axis_reversed": false,
          "plot_size_by_field": false,
          "trellis": "",
          "stacking": "",
          "limit_displayed_rows": false,
          "legend_position": "center",
          "point_style": "none",
          "show_value_labels": false,
          "label_density": 25,
          "x_axis_scale": "auto",
          "y_axis_combined": true,
          "show_null_points": true,
          "interpolation": "linear",
          "defaults_version": 1,
          "series_types": {},
          "ordering": "none",
          "show_null_labels": false,
          "show_totals_labels": false,
          "show_silhouette": false,
          "totals_color": "#808080"
        },
        "filter_config": {},
        "visible_ui_sections": null,
        "slug": "njXD4SW",
        "dynamic_fields": null,
        "client_id": "kZZsynIfkhfrKvPoiu5SEQ",
        "share_url": "https://self-signed.looker.com:9999/x/kZZsynIfkhfrKvPoiu5SEQ",
        "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/orders?fields=orders.created_date,orders.average_total_amount_of_order_usd&fill_fields=orders.created_date&sorts=orders.created_date+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22custom_color_enabled%22%3Atrue%2C%22show_single_value_title%22%3Atrue%2C%22show_comparison%22%3Afalse%2C%22comparison_type%22%3A%22value%22%2C%22comparison_reverse_colors%22%3Afalse%2C%22show_comparison_label%22%3Atrue%2C%22enable_conditional_formatting%22%3Afalse%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%2C%22type%22%3A%22single_value%22%2C%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D&origin=share-expanded",
        "query_timezone": "America/Los_Angeles",
        "runtime": null,
        "model": "thelook"
      },
      "query_id": 395,
      "refresh_interval": null,
      "refresh_interval_to_i": null,
      "result_maker_id": 84,
      "subtitle_text": null,
      "title": "Average order amount today",
      "title_hidden": false,
      "title_text": null,
      "type": "vis",
      "alert_count": 0,
      "title_text_as_html": null,
      "subtitle_text_as_html": null,
      "result_maker": {
        "id": 84,
        "dynamic_fields": null,
        "filterables": [
          {
            "model": "thelook",
            "view": "orders",
            "name": null,
            "listen": [
              {
                "dashboard_filter_name": "Created Date",
                "field": "orders.created_date"
              }
            ]
          }
        ],
        "sorts": [
          "orders.created_date desc"
        ],
        "merge_result_id": null,
        "total": null,
        "query_id": 395,
        "sql_query_id": null,
        "query": {
          "id": 395,
          "view": "orders",
          "fields": [
            "orders.created_date",
            "orders.average_total_amount_of_order_usd"
          ],
          "pivots": null,
          "fill_fields": [
            "orders.created_date"
          ],
          "filters": null,
          "filter_expression": null,
          "sorts": [
            "orders.created_date desc"
          ],
          "limit": "500",
          "column_limit": null,
          "total": null,
          "row_total": null,
          "subtotals": null,
          "vis_config": {
            "custom_color_enabled": true,
            "show_single_value_title": true,
            "show_comparison": false,
            "comparison_type": "value",
            "comparison_reverse_colors": false,
            "show_comparison_label": true,
            "enable_conditional_formatting": false,
            "conditional_formatting_include_totals": false,
            "conditional_formatting_include_nulls": false,
            "type": "single_value",
            "x_axis_gridlines": false,
            "y_axis_gridlines": true,
            "show_view_names": false,
            "show_y_axis_labels": true,
            "show_y_axis_ticks": true,
            "y_axis_tick_density": "default",
            "y_axis_tick_density_custom": 5,
            "show_x_axis_label": true,
            "show_x_axis_ticks": true,
            "y_axis_scale_mode": "linear",
            "x_axis_reversed": false,
            "y_axis_reversed": false,
            "plot_size_by_field": false,
            "trellis": "",
            "stacking": "",
            "limit_displayed_rows": false,
            "legend_position": "center",
            "point_style": "none",
            "show_value_labels": false,
            "label_density": 25,
            "x_axis_scale": "auto",
            "y_axis_combined": true,
            "show_null_points": true,
            "interpolation": "linear",
            "defaults_version": 1,
            "series_types": {},
            "ordering": "none",
            "show_null_labels": false,
            "show_totals_labels": false,
            "show_silhouette": false,
            "totals_color": "#808080"
          },
          "filter_config": {},
          "visible_ui_sections": null,
          "slug": "njXD4SW",
          "dynamic_fields": null,
          "client_id": "kZZsynIfkhfrKvPoiu5SEQ",
          "share_url": "https://self-signed.looker.com:9999/x/kZZsynIfkhfrKvPoiu5SEQ",
          "expanded_share_url": "https://self-signed.looker.com:9999/explore/thelook/orders?fields=orders.created_date,orders.average_total_amount_of_order_usd&fill_fields=orders.created_date&sorts=orders.created_date+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22custom_color_enabled%22%3Atrue%2C%22show_single_value_title%22%3Atrue%2C%22show_comparison%22%3Afalse%2C%22comparison_type%22%3A%22value%22%2C%22comparison_reverse_colors%22%3Afalse%2C%22show_comparison_label%22%3Atrue%2C%22enable_conditional_formatting%22%3Afalse%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%2C%22type%22%3A%22single_value%22%2C%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D&origin=share-expanded",
          "url": "/explore/thelook/orders?fields=orders.created_date,orders.average_total_amount_of_order_usd&fill_fields=orders.created_date&sorts=orders.created_date+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22custom_color_enabled%22%3Atrue%2C%22show_single_value_title%22%3Atrue%2C%22show_comparison%22%3Afalse%2C%22comparison_type%22%3A%22value%22%2C%22comparison_reverse_colors%22%3Afalse%2C%22show_comparison_label%22%3Atrue%2C%22enable_conditional_formatting%22%3Afalse%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%2C%22type%22%3A%22single_value%22%2C%22x_axis_gridlines%22%3Afalse%2C%22y_axis_gridlines%22%3Atrue%2C%22show_view_names%22%3Afalse%2C%22show_y_axis_labels%22%3Atrue%2C%22show_y_axis_ticks%22%3Atrue%2C%22y_axis_tick_density%22%3A%22default%22%2C%22y_axis_tick_density_custom%22%3A5%2C%22show_x_axis_label%22%3Atrue%2C%22show_x_axis_ticks%22%3Atrue%2C%22y_axis_scale_mode%22%3A%22linear%22%2C%22x_axis_reversed%22%3Afalse%2C%22y_axis_reversed%22%3Afalse%2C%22plot_size_by_field%22%3Afalse%2C%22trellis%22%3A%22%22%2C%22stacking%22%3A%22%22%2C%22limit_displayed_rows%22%3Afalse%2C%22legend_position%22%3A%22center%22%2C%22point_style%22%3A%22none%22%2C%22show_value_labels%22%3Afalse%2C%22label_density%22%3A25%2C%22x_axis_scale%22%3A%22auto%22%2C%22y_axis_combined%22%3Atrue%2C%22show_null_points%22%3Atrue%2C%22interpolation%22%3A%22linear%22%2C%22defaults_version%22%3A1%2C%22series_types%22%3A%7B%7D%2C%22ordering%22%3A%22none%22%2C%22show_null_labels%22%3Afalse%2C%22show_totals_labels%22%3Afalse%2C%22show_silhouette%22%3Afalse%2C%22totals_color%22%3A%22%23808080%22%7D&filter_config=%7B%7D",
          "query_timezone": "America/Los_Angeles",
          "runtime": null,
          "has_table_calculations": false,
          "model": "thelook",
          "can": {
            "run": true,
            "see_results": true,
            "explore": true,
            "create": true,
            "show": true,
            "cost_estimate": true,
            "index": true,
            "see_lookml": true,
            "see_aggregate_table_lookml": true,
            "see_derived_table_lookml": true,
            "see_sql": true,
            "generate_drill_links": true,
            "download": true,
            "download_unlimited": true,
            "schedule": true,
            "render": true
          }
        },
        "vis_config": {
          "custom_color_enabled": true,
          "show_single_value_title": true,
          "show_comparison": false,
          "comparison_type": "value",
          "comparison_reverse_colors": false,
          "show_comparison_label": true,
          "enable_conditional_formatting": false,
          "conditional_formatting_include_totals": false,
          "conditional_formatting_include_nulls": false,
          "type": "single_value",
          "x_axis_gridlines": false,
          "y_axis_gridlines": true,
          "show_view_names": false,
          "show_y_axis_labels": true,
          "show_y_axis_ticks": true,
          "y_axis_tick_density": "default",
          "y_axis_tick_density_custom": 5,
          "show_x_axis_label": true,
          "show_x_axis_ticks": true,
          "y_axis_scale_mode": "linear",
          "x_axis_reversed": false,
          "y_axis_reversed": false,
          "plot_size_by_field": false,
          "trellis": "",
          "stacking": "",
          "limit_displayed_rows": false,
          "legend_position": "center",
          "point_style": "none",
          "show_value_labels": false,
          "label_density": 25,
          "x_axis_scale": "auto",
          "y_axis_combined": true,
          "show_null_points": true,
          "interpolation": "linear",
          "defaults_version": 1,
          "series_types": {},
          "ordering": "none",
          "show_null_labels": false,
          "show_totals_labels": false,
          "show_silhouette": false,
          "totals_color": "#808080"
        }
      },
      "can": {
        "create": true,
        "update": true,
        "destroy": true,
        "see_aggregate_table_lookml": true,
        "index": true,
        "show": true,
        "explore": true,
        "run": false,
        "show_errors": true,
        "find_and_replace": true
      }
    },
    {
      "body_text": null,
      "body_text_as_html": null,
      "dashboard_id": 59,
      "edit_uri": null,
      "id": 111,
      "look": null,
      "look_id": null,
      "lookml_link_id": null,
      "merge_result_id": null,
      "note_display": null,
      "note_state": null,
      "note_text": null,
      "note_text_as_html": null,
      "query": {
        "id": 425,
        "view": "order_items",
        "fields": [
          "order_items.count"
        ],
        "pivots": null,
        "fill_fields": null,
        "filters": {
          "order_items.returned": "Yes"
        },
        "filter_expression": null,
        "sorts": [
          "order_items.count desc"
        ],
        "limit": "500",
        "column_limit": null,
        "total": null,
        "row_total": null,
        "vis_config": {
          "custom_color_enabled": true,
          "show_single_value_title": true,
          "show_comparison": false,
          "comparison_type": "value",
          "comparison_reverse_colors": false,
          "show_comparison_label": true,
          "enable_conditional_formatting": false,
          "conditional_formatting_include_totals": false,
          "conditional_formatting_include_nulls": false,
          "type": "single_value",
          "defaults_version": 1
        },
        "filter_config": {
          "order_items.returned": [
            {
              "type": "is",
              "values": [
                {
                  "constant": "Yes"
                },
                {}
              ],
              "id": 0
            }
          ]
        },
        "visible_ui_sections": null,
        "slug": "TxVcB48",
        "dynamic_fields": null,
        "client_id": "pLSFg1yqvS1YjmmUOHoTRE",
        "share_url": "https://self-signed.looker.com:9999/x/pLSFg1yqvS1YjmmUOHoTRE",
        "expanded_share_url": "https://self-signed.looker.com:9999/explore/test/order_items?fields=order_items.count&f[order_items.returned]=Yes&sorts=order_items.count+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22custom_color_enabled%22%3Atrue%2C%22show_single_value_title%22%3Atrue%2C%22show_comparison%22%3Afalse%2C%22comparison_type%22%3A%22value%22%2C%22comparison_reverse_colors%22%3Afalse%2C%22show_comparison_label%22%3Atrue%2C%22enable_conditional_formatting%22%3Afalse%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%2C%22type%22%3A%22single_value%22%2C%22defaults_version%22%3A1%7D&filter_config=%7B%22order_items.returned%22%3A%5B%7B%22type%22%3A%22is%22%2C%22values%22%3A%5B%7B%22constant%22%3A%22Yes%22%7D%2C%7B%7D%5D%2C%22id%22%3A0%7D%5D%7D&origin=share-expanded",
        "query_timezone": "America/Los_Angeles",
        "runtime": null,
        "model": "test"
      },
      "query_id": 425,
      "refresh_interval": null,
      "refresh_interval_to_i": null,
      "result_maker_id": 85,
      "subtitle_text": null,
      "title": "Lifetime Returns",
      "title_hidden": false,
      "title_text": null,
      "type": "vis",
      "alert_count": 0,
      "title_text_as_html": null,
      "subtitle_text_as_html": null,
      "result_maker": {
        "id": 85,
        "dynamic_fields": null,
        "filterables": [
          {
            "model": "test",
            "view": "order_items",
            "name": null,
            "listen": []
          }
        ],
        "sorts": [
          "order_items.count desc"
        ],
        "merge_result_id": null,
        "total": null,
        "query_id": 425,
        "sql_query_id": null,
        "query": {
          "id": 425,
          "view": "order_items",
          "fields": [
            "order_items.count"
          ],
          "pivots": null,
          "fill_fields": null,
          "filters": {
            "order_items.returned": "Yes"
          },
          "filter_expression": null,
          "sorts": [
            "order_items.count desc"
          ],
          "limit": "500",
          "column_limit": null,
          "total": null,
          "row_total": null,
          "subtotals": null,
          "vis_config": {
            "custom_color_enabled": true,
            "show_single_value_title": true,
            "show_comparison": false,
            "comparison_type": "value",
            "comparison_reverse_colors": false,
            "show_comparison_label": true,
            "enable_conditional_formatting": false,
            "conditional_formatting_include_totals": false,
            "conditional_formatting_include_nulls": false,
            "type": "single_value",
            "defaults_version": 1
          },
          "filter_config": {
            "order_items.returned": [
              {
                "type": "is",
                "values": [
                  {
                    "constant": "Yes"
                  },
                  {}
                ],
                "id": 0
              }
            ]
          },
          "visible_ui_sections": null,
          "slug": "TxVcB48",
          "dynamic_fields": null,
          "client_id": "pLSFg1yqvS1YjmmUOHoTRE",
          "share_url": "https://self-signed.looker.com:9999/x/pLSFg1yqvS1YjmmUOHoTRE",
          "expanded_share_url": "https://self-signed.looker.com:9999/explore/test/order_items?fields=order_items.count&f[order_items.returned]=Yes&sorts=order_items.count+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22custom_color_enabled%22%3Atrue%2C%22show_single_value_title%22%3Atrue%2C%22show_comparison%22%3Afalse%2C%22comparison_type%22%3A%22value%22%2C%22comparison_reverse_colors%22%3Afalse%2C%22show_comparison_label%22%3Atrue%2C%22enable_conditional_formatting%22%3Afalse%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%2C%22type%22%3A%22single_value%22%2C%22defaults_version%22%3A1%7D&filter_config=%7B%22order_items.returned%22%3A%5B%7B%22type%22%3A%22is%22%2C%22values%22%3A%5B%7B%22constant%22%3A%22Yes%22%7D%2C%7B%7D%5D%2C%22id%22%3A0%7D%5D%7D&origin=share-expanded",
          "url": "/explore/test/order_items?fields=order_items.count&f[order_items.returned]=Yes&sorts=order_items.count+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22custom_color_enabled%22%3Atrue%2C%22show_single_value_title%22%3Atrue%2C%22show_comparison%22%3Afalse%2C%22comparison_type%22%3A%22value%22%2C%22comparison_reverse_colors%22%3Afalse%2C%22show_comparison_label%22%3Atrue%2C%22enable_conditional_formatting%22%3Afalse%2C%22conditional_formatting_include_totals%22%3Afalse%2C%22conditional_formatting_include_nulls%22%3Afalse%2C%22type%22%3A%22single_value%22%2C%22defaults_version%22%3A1%7D&filter_config=%7B%22order_items.returned%22%3A%5B%7B%22type%22%3A%22is%22%2C%22values%22%3A%5B%7B%22constant%22%3A%22Yes%22%7D%2C%7B%7D%5D%2C%22id%22%3A0%7D%5D%7D",
          "query_timezone": "America/Los_Angeles",
          "runtime": null,
          "has_table_calculations": false,
          "model": "test",
          "can": {
            "run": true,
            "see_results": true,
            "explore": true,
            "create": true,
            "show": true,
            "cost_estimate": true,
            "index": true,
            "see_lookml": true,
            "see_aggregate_table_lookml": true,
            "see_derived_table_lookml": true,
            "see_sql": true,
            "generate_drill_links": true,
            "download": true,
            "download_unlimited": true,
            "schedule": true,
            "render": true
          }
        },
        "vis_config": {
          "custom_color_enabled": true,
          "show_single_value_title": true,
          "show_comparison": false,
          "comparison_type": "value",
          "comparison_reverse_colors": false,
          "show_comparison_label": true,
          "enable_conditional_formatting": false,
          "conditional_formatting_include_totals": false,
          "conditional_formatting_include_nulls": false,
          "type": "single_value",
          "defaults_version": 1
        }
      },
      "can": {
        "create": true,
        "update": true,
        "destroy": true,
        "see_aggregate_table_lookml": true,
        "index": true,
        "show": true,
        "explore": true,
        "run": false,
        "show_errors": true,
        "find_and_replace": true
      }
    }
  ],
  "dashboard_filters": [
    {
      "id": 3,
      "dashboard_id": 59,
      "name": "Created Date",
      "title": "Created Date",
      "type": "field_filter",
      "default_value": "2019/01/01 to 2019/12/23",
      "explore": "orders",
      "dimension": "orders.created_date",
      "row": 1,
      "allow_multiple_values": true,
      "required": false,
      "ui_config": {
        "type": "relative_timeframes",
        "display": "inline",
        "options": []
      },
      "model": "thelook",
      "listens_to_filters": [],
      "field": {
        "align": "left",
        "can_filter": true,
        "category": "dimension",
        "default_filter_value": null,
        "description": null,
        "enumerations": null,
        "field_group_label": "Created Date",
        "fill_style": "range",
        "fiscal_month_offset": 0,
        "has_allowed_values": false,
        "hidden": false,
        "is_filter": false,
        "is_numeric": false,
        "label": "Orders Created Date",
        "label_from_parameter": null,
        "label_short": "Created Date",
        "lookml_link": "/projects/thelook/files/views_core%2Forders.view.lkml?line=73",
        "map_layer": null,
        "name": "orders.created_date",
        "strict_value_format": false,
        "permanent": null,
        "requires_refresh_on_sort": false,
        "sortable": true,
        "suggestions": null,
        "tags": [],
        "type": "date_date",
        "user_attribute_filter_types": [
          "datetime",
          "advanced_filter_datetime"
        ],
        "value_format": null,
        "view": "orders",
        "view_label": "Orders",
        "dynamic": false,
        "week_start_day": "monday",
        "error": null,
        "field_group_variant": "Date",
        "measure": false,
        "parameter": false,
        "primary_key": false,
        "project_name": "thelook",
        "scope": "orders",
        "source_file": "views_core/orders.view.lkml",
        "source_file_path": "thelook/views_core/orders.view.lkml",
        "suggest_dimension": "orders.created_date",
        "suggest_explore": "orders",
        "suggestable": false,
        "is_fiscal": false,
        "is_timeframe": true,
        "can_time_filter": false,
        "time_interval": {
          "name": "day",
          "count": 1
        },
        "sql": null,
        "sql_case": null
      }
    }
  ],
  "dashboard_layouts": [
    {
      "id": 59,
      "dashboard_id": 59,
      "type": "newspaper",
      "active": true,
      "column_width": null,
      "width": null,
      "deleted": false,
      "dashboard_layout_components": [
        {
          "id": 106,
          "dashboard_layout_id": 59,
          "dashboard_element_id": 106,
          "row": 3,
          "column": 0,
          "width": 19,
          "height": 6,
          "deleted": false
        },
        {
          "id": 108,
          "dashboard_layout_id": 59,
          "dashboard_element_id": 108,
          "row": 3,
          "column": 19,
          "width": 5,
          "height": 6,
          "deleted": false
        },
        {
          "id": 111,
          "dashboard_layout_id": 59,
          "dashboard_element_id": 111,
          "row": 0,
          "column": 21,
          "width": 3,
          "height": 3,
          "deleted": false
        },
        {
          "id": 107,
          "dashboard_layout_id": 59,
          "dashboard_element_id": 107,
          "row": 9,
          "column": 0,
          "width": 19,
          "height": 6,
          "deleted": false
        },
        {
          "id": 110,
          "dashboard_layout_id": 59,
          "dashboard_element_id": 110,
          "row": 0,
          "column": 0,
          "width": 21,
          "height": 3,
          "deleted": false
        },
        {
          "id": 109,
          "dashboard_layout_id": 59,
          "dashboard_element_id": 109,
          "row": 9,
          "column": 19,
          "width": 5,
          "height": 6,
          "deleted": false
        }
      ]
    }
  ],
  "deleted_at": null,
  "deleter_id": null,
  "edit_uri": null,
  "favorite_count": 0,
  "last_accessed_at": "2020-06-17T12:26:44.955-07:00",
  "load_configuration": "cache_run",
  "show_filters_bar": null,
  "show_title": null,
  "slug": "Bcx8CvBO86U6DI4jYZseJi",
  "space_id": 1,
  "text_tile_text_color": null,
  "tile_background_color": null,
  "tile_text_color": null,
  "title_color": null,
  "view_count": 3,
  "preferred_viewer": "dashboards-next",
  "content_favorite_id": null,
  "model": null,
  "deleted": false,
  "last_viewed_at": "2020-06-17T12:28:58.730-07:00",
  "can": {
    "download": true,
    "see_aggregate_table_lookml": true,
    "index": true,
    "show": true,
    "copy": true,
    "run": true,
    "create": true,
    "move": true,
    "update": true,
    "destroy": true,
    "recover": true,
    "see_lookml": true,
    "schedule": true,
    "render": true
  }
}
